# Generated by Django 3.2 on 2021-04-10 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyGallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 10, 17, 6, 58, 644496)),
        ),
    ]
